### ISSUE TITLE
Unicode package to install?

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/fstar-mode.el#1]
Trying this out ... looks great! 

However, it seems I don't have all the Unicode symbols available for rendering this properly on my machine. For example, the rendering of `nat` as a bb N doesn't show up for me (I just get a box). 

What are the recommended Unicode settings for using this mode?

Thanks!

**Comment by jkzinzindohoue** [comment]
I had the same issue, I think that emacs default font does not support some of the unicode characters. Installing Deja Vu Sans Mono and setting it as my default font did it for me : 
http://dejavu-fonts.org/wiki/Download

I added `(add-to-list 'default-frame-alist '(font . "DejaVu Sans Mono-10"))` to the `.emacs`.

The rest works pretty well, thanks !

**Comment by cpitclaudel** [comment]
Indeed, it's a font issue. Emacs doesn't really come with a default font; it uses the system one, and resorts to font fallback when the default font doesn't cover a particular character.

What this means is that just installing a font with good coverage should normally be enough to get the symbols to display properly. That doesn't always cut it, though (there are some small issues with font fallback, on Windows in particular).

DejaVu Sans Mono, [Symbola](http://shapecatcher.com/downloads/Symbola706.zip), FreeMono, STIX, Unifont, Segoe UI Symbol, Arial Unicode and Cambria Math are all good candidates. If Emacs doesn't pick up on the new fonts after a restart, the following snippet should help:

```elisp
(set-fontset-font t 'unicode (font-spec :name "SOME FONT WITH GOOD COVERAGE") nil 'append)
```
