### ISSUE TITLE
Forcing specific fonts for certain symbols

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/fstar-mode.el#10]
Hi Clement, 

You may have shown me how to do this in person ... but I've forgotten. 

Is there a way to force emacs to choose a certain font for rendering particular symbols. For example, I'd like the `forall` symbol to come from Symbola but the `lambda` to come from Consolas. 

The only thing I am able to do is to set the fonts in some order so that it picks, say, Consolas first, if the symbol exists there, and uses Symbola otherwise. But, this is not specific to the particular characters I care about. 

Please answer at your leisure. 

Enjoying this emacs mode a lot!

Thanks, 
Nik

**Comment by cpitclaudel** [comment]
Hey Nik,

Try this:
```elisp
(set-fontset-font t (cons ?∀ ?∀) "Symbola" nil 'prepend)
```

I'll add it to the README.

**Comment by cpitclaudel** [comment]
Closing this issue; let me know if the snippet above doesn't do it :) I've also updated the README.

**Comment by nikswamy** [comment]
Very late response. Thanks for the suggestion ... it works well.
