### ISSUE TITLE
Code that typechecks normally from the command line can crash fstar-mode

### ISSUE THREAD

**Issue by Azelef** [FStarLang/fstar-mode.el#109]
The following code (put in a file called Foo.fst) can be typechecked normally with the 
```
fstar.exe Foo.fst
```
command, but when the last line is typechecked in fstar-mode, it crashes and the subprocess must be killed.

```
module Foo

open FStar.Buffer

let wat buff =assert( buff.(0ul) % 2 = 0)
```
Also, the following error message appears in emacs : "error in process filter : Not enough arguments for format string".

**Comment by cpitclaudel** [comment]
Thanks for the report!
