### ISSUE TITLE
Add .fsti extension to auto-mode-alist

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/fstar-mode.el#11]
It's missing

**Comment by cpitclaudel** [comment]
What's the full list of extensions? `fst`, `fsi`, `fsti`?

**Comment by catalin-hritcu** [comment]
Just `fst` and `fsti` (`fsi` is F#)

**Comment by cpitclaudel** [comment]
Done, thanks!

**Comment by aseemr** [comment]
fsi is also a valid extension for F* interfaces.

**Comment by catalin-hritcu** [comment]
Maybe we should rename them then ...

**Comment by aseemr** [comment]
Why.

**Comment by catalin-hritcu** [comment]
Because that extension is already taken by a much more popular tool, which can be very confusing.

**Comment by catalin-hritcu** [comment]
For instance have a look at this: https://github.com/github/linguist/pull/2590

**Comment by beurdouche** [comment]
I am personally in favour of using .fsti for files which contains F* code and .fsi for things which is F# or common syntactic subset.

**Comment by cpitclaudel** [comment]
Is there any reason to open files in the common subset as F* files in Emacs, though? Wouldn't we want to leave these to fsharp-mode?

**Comment by catalin-hritcu** [comment]
> Is there any reason to open files in the common subset as F* files in Emacs, though?  Wouldn't we want to leave these to fsharp-mode?

If they are F# is there any reason not to open them as F#? :)

**Comment by cpitclaudel** [comment]
@catalin-hritcu I agree, but I'm not an F* programmer, so I can't really say :) As a package developer, I'd rather reduce the overlap with other packages; users should feel free to add the file association themselves. I'll add a note in the README.
