### ISSUE TITLE
`nil` confusion

### ISSUE THREAD

**Issue by mtzguido** [FStarLang/fstar-mode.el#116]
Silly issue, but if I define an identifier with the name `nil` and try to `C-c C-s C-p` wtih the cursor over it, no default is autocompleted:

![2020-03-05 13:16:57_236](https://user-images.githubusercontent.com/4195583/76001353-bbd35d80-5ee3-11ea-95a9-1170b309ff8d.png)

For other names the feature works well of course.

![2020-03-05 13:17:19_237](https://user-images.githubusercontent.com/4195583/76001388-cc83d380-5ee3-11ea-9983-3e503927e835.png)

 One can also write "nil" manually to circumvent this issue.

**Comment by cpitclaudel** [comment]
Ouch, thanks for the report.

**Comment by mtzguido** [comment]
Thanks, that was fast!
