### ISSUE TITLE
Different errors between interactive mode and batch mode

### ISSUE THREAD

**Issue by msprotz** [FStarLang/fstar-mode.el#13]
```
module Test

open Heap

type content =
| Link: ref content -> content
| Root: content

val repr: content -> content
let rec repr x =
  match x with
  | Link r ->
    repr !r
  | Root ->
    root
```

With the fstar-mode: `identifier not found: ref`
With the fstar batch compiler: `identifier not found: root` (that's the right error).

**Comment by catalin-hritcu** [comment]
How is the interactive supposed to know that you need `heaf.fst` for this? Try including a `build-config` like this:
```
(*--build-config
    options:--admit_fsi FStar.Set;
    other-files:set.fsi heap.fst
  --*)
```

**Comment by catalin-hritcu** [comment]
Ah I see, you probably rely on F* automatically including some standard library files when a single file is passed from the command line, which seems to not happen when the `-in` flag is passed. Automatically including random standard library files seems like a bad idea, doing it in some cases but not in others is even worse, you can file this usability problem against F*.

**Comment by msprotz** [comment]
I'd argue that it's great that F* found the `fsi` file automatically. OCaml also finds ".mli" files in the include path (lib directory, current directory), and I would be awful if we had to specify the list of all the .mli files we need when type-checking an OCaml file. I'll file an issue against F*.

**Comment by catalin-hritcu** [comment]
Please define "matching" fst/fsi file.
