### ISSUE TITLE
Line-wrapping in comments

### ISSUE THREAD

**Issue by msprotz** [FStarLang/fstar-mode.el#15]
I turn on auto-fill so that my comments wrap after a while. However, in the fstar-mode, every time auto-fill wraps into a new line, I get:

```
(* foo ... long line
  (* ⬚
```

Where ⬚ is the position of the cursor. Notice 1) the extra indentation and 2) the undesired `(*`.

Desired behavior: either

```
(* foo ... long line
 * ⬚
```

or

```
(* foo ... long line
   ⬚
```

Thanks,

Jonathan

**Comment by cpitclaudel** [comment]
I've pushed a tentative fix for this. It should be on MELPA in a few hours; let me know if it works!

**Comment by msprotz** [comment]
Yes it does. Thanks!
