### ISSUE TITLE
Don't strip (*--build-config ... *) comments!

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/fstar-mode.el#17]
These are comments, so 7c16a9cfb932db36268ab089ed0123efd0c481aa strips them, but they should be an exception.

**Comment by cpitclaudel** [comment]
Does it?

**Comment by s-zanella** [comment]
It looks like the code you pushed is suppossed to not strip them, but it does strip them.

**Comment by cpitclaudel** [comment]
Oups

**Comment by cpitclaudel** [comment]
Indeed, that code is broken. Thanks.

**Comment by s-zanella** [comment]
No worries. Thanks!

**Comment by cpitclaudel** [comment]
Should work now (hopefully)
