### ISSUE TITLE
Disabling specific character substitutions

### ISSUE THREAD

**Issue by hoheinzollern** [FStarLang/fstar-mode.el#18]
Hi Clement,
thanks a lot for this Emacs mode, it's my favourite :)

Emacs for Mac recently got support for font ligatures, and there are cool fonts like [Fira](http://mozilla.github.io/Fira/) and [Hasklig](https://github.com/i-tu/Hasklig) that offer substitutions for character combinations that look better than their single character counterparts.
It would be great to disable character substitution for those specific cases, would that be possible to configure through some Emacs settings?

**Comment by cpitclaudel** [comment]
Hi there,

Disabling substitutions entirely should be easy; just use `M-x customize-variable RET fstar-enabled-modules` and uncheck the relevant box. For more fine-grained control I've just pushed a patch that makes `fstar-symbols-alist` customizable, so you can use `M-x customize-variable RET fstar-symbols-alist` to remove specific substitutions. Let me know if that works!

**Comment by nikswamy** [comment]
I have trouble with the characters 10233 and 10234, the substitutions for ==> and <==>
http://www.codetable.net/decimal/10233

I have this in my .emacs
```
(set-fontset-font t 'unicode (font-spec :name "Symbola") nil 'append)
(set-fontset-font t 'unicode (font-spec :name "Consolas") nil 'append)
(set-fontset-font t (cons ?∀ ?∀) "Symbola" nil 'prepend)
(set-fontset-font t (cons ?≠ ?≠) "Consolas" nil 'prepend)
```

I guess it's trying to pick 10233 from Symbola. Now, I try to add this:

```
(set-fontset-font t '(#x27f9 #x27f9) "Consolas" nil 'prepend)
```

But this fails with a "Wrong type argument: characterp, 10233"

Any suggestions?

**Comment by cpitclaudel** [comment]
Yes! Try `(set-fontset-font t '(#x27f9 . #x27f9) "Consolas" nil 'prepend)` (notice the additional dot).
