### ISSUE TITLE
File mode specification error: (void-function fstar-setup-prettify)

### ISSUE THREAD

**Issue by thsutton** [FStarLang/fstar-mode.el#2]
I'm getting started with FStar at the CUFP tutorial and attempting to use this emacs mode results in the following message when I load a .fst file: `File mode specification error: (void-function fstar-setup-prettify)`.

I installed the mode by using:

````
git clone https://github.com/FStarLang/fstar-mode.el ~/.emacs.d/site-lisp/fstar-mode
echo "(require 'fstar-mode ]"~/.emacs.d/site-lisp/fstar-mode/fstar-mode.el\")" >> ~/.emacs
````

**Comment by cpitclaudel** [comment]
Ah, yes, sorry about that. I forgot to push a small fix.

**Comment by cpitclaudel** [comment]
It should be fixed in a few minutes

**Comment by cpitclaudel** [comment]
Can you try pulling again now?

**Comment by thsutton** [comment]
It's fixed now. Thanks!

**Comment by cpitclaudel** [comment]
Awesome! Enjoy F* programming :)
