### ISSUE TITLE
Symbol for :: (cons)?

### ISSUE THREAD

**Issue by msprotz** [FStarLang/fstar-mode.el#22]
I have the blank square issue, but I'm using the recommended font (DejaVu Sans). Which fonts have the "cons" symbol? Is it possible to disable this symbol only?

Thanks,

Jonathan

**Comment by cpitclaudel** [comment]
Mine comes from Symbola. You can selectively disable symbols using `M-x customize-variable RET fstar-symbols-alist RET`. Maybe I should just remove that symbol.

**Comment by msprotz** [comment]
This Symbola? https://github.com/zhm/symbola/tree/master/fonts

**Comment by cpitclaudel** [comment]
This one: http://shapecatcher.com/downloads/Symbola706.zip

**Comment by msprotz** [comment]
Thanks. I've edited the README.md to point to the right symbola font (there were quite a few different results from a search engine).
