### ISSUE TITLE
Found a repro case for sending F* into a bad state

### ISSUE THREAD

**Issue by msprotz** [FStarLang/fstar-mode.el#23]
```

(** Some extra helper functions for lists. *)

module ListSet

open FStar.List

let _ = "foo"

(** [lsubset la lb] is true if and only if all the elements from [la]
    are also in [lb]. *)
val lsubset: #a:Type -> list a -> list a -> Tot bool
let rec lsubset la lb =
match la with
| [] -> true
| h :: tl ->  ((mem h lb) && (lsubset tl lb))
```

Hit C-c C-n. Get "Unexpected pattern at the top-level".

Fix it by removing the "let _ = foo" line. Hit C-c C-n. Get "Identifier not found: [mem].".

Kill the sub-process. Hit C-c C-n again. Everything works fine.

**Comment by cpitclaudel** [comment]
Hmm. I'm always getting the "Identifier not found" message actually, even after restarting F*. Am I doing something wrong?

**Comment by msprotz** [comment]
Hmm you probably don't have `ListSet`. Let me try to craft a more minimal testcase.

**Comment by cpitclaudel** [comment]
Sprint cleaning! This example works for me now, so I'll close this :) Feel free to reopen if it's still broken.
