### ISSUE TITLE
v vs. ∨

### ISSUE THREAD

**Issue by msprotz** [FStarLang/fstar-mode.el#24]
The two symbols are really close to each other visually. Is there any way you could make ∨ bold to distinguish it from the variable v? Or perhaps in a different color.

Thanks!

Jonathan

**Comment by cpitclaudel** [comment]
I pushed a change in that direction. `fstar-ambiguous-face` is now applied to `/\` and `\/`. By default it inherits from `font-lock-negation-char-face`, which is usually just bold. Feel free to customize that face and tell me if you find a better way to disambiguate :)

Another approach is to use
```
(set-fontset-font t (cons ?∨ ?∨) "Symbola" nil 'prepend)
```
or
```
(set-fontset-font t (cons ?∨ ?∨) "FreeMono" nil 'prepend)
```
as these fonts have much more readable symbols.

**Comment by msprotz** [comment]
I didn't notice any change after upgrading fstar-mode, but "another approach" worked fine for me.

Thanks!

**Comment by cpitclaudel** [comment]
Sure. I'll close this then, and anyone with the same problem should feel free to reopen.
