### ISSUE TITLE
Command to kill F* process in all buffers?

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/fstar-mode.el#25]
Would be great to have a command to kill all running F* processes. 

I currently have to search through all my buffers killing F* in each one each time I want to rebuild the F* binary.

**Comment by cpitclaudel** [comment]
Done :) C-u C-c C-x will do it. The update should be in MELPA in a few hours, let me know if it works!

**Comment by nikswamy** [comment]
thanks!
