### ISSUE TITLE
Warnings on updating fstar-mode

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/fstar-mode.el#27]
I did a list-packages, chose fstar-mode, and clicked on Install. I got the messages below. Is this expected? Or, should I fix my emacs configuration in some way?

```
Compiling file c:/Users/nswamy/.emacs.d/elpa/fstar-mode-20151023.753/fstar-mode-pkg.el at Wed Oct 28 07:58:21 2015
Entering directory `c:/Users/nswamy/.emacs.d/elpa/fstar-mode-20151023.753/'

Compiling file c:/Users/nswamy/.emacs.d/elpa/fstar-mode-20151023.753/fstar-mode.el at Wed Oct 28 07:58:21 2015
fstar-mode.el:99:17:Warning: reference to free variable `flycheck-checkers'
fstar-mode.el:99:17:Warning: assignment to free variable `flycheck-checkers'

In fstar-setup-interactive:
fstar-mode.el:1132:19:Warning: reference to free variable
    `flycheck-disabled-checkers'
fstar-mode.el:1132:19:Warning: assignment to free variable
    `flycheck-disabled-checkers'

In end of data:
fstar-mode.el:1214:1:Warning: the following functions are not known to be defined:
    flycheck-define-command-checker,
    flycheck-increment-error-columns, flycheck-mode
```

**Comment by cpitclaudel** [comment]
Hey Nik,

Could this be an old Emacs?

**Comment by nikswamy** [comment]
I'm using GNU Emacs 24.5.1 (i686-pc-mingw32)

**Comment by cpitclaudel** [comment]
Everything is fine then; I just need to review my definition of "old Emacs" :)
The offending code looks like this:

```
(when (featurep 'flycheck)
  (do-something-that-requires-flycheck))
```

The trick is that the warnings in Emacs < 25 are not smart enough to see that the code is surrounded by a `(featurep)` check. This code won't run unless flycheck is installed, and then it will be fine. Flycheck was useful for real-time checking of small files, but the interactive mode mostly replaced it now.
