### ISSUE TITLE
Interactive mode spits "Beginning of buffer" error if buffer starts with double slashes

### ISSUE THREAD

**Issue by wizeman** [FStarLang/fstar-mode.el#30]
As mentioned in the title, if a file starts with `// ` then the interactive mode commands `C-c C-RET` and `C-c C-n` simply show a `seq: Beginning of buffer` error in the `Messages` buffer, but don't do any actual checking.

I've tried to debug this even though I don't know much about Emacs or Lisp, and as far as I could tell (using Emacs' debugger) the error seems to come from this line of code:

https://github.com/FStarLang/fstar-mode.el/blob/5e7c3d5a4b5422284d8ef4b69023b1fd71952b81/fstar-mode.el#L860

More specifically, it seems that the error gets thrown by the `comment-search-forward` function, if I'm not mistaken (that's how I figured the error had something to do with comments).

**Comment by cpitclaudel** [comment]
Thanks for the report! You were spot on. Turns out the auto-detection mechanism for comments isn't as smart as I thought.
I pushed (what is hopefully) a fix; can you give it a try?

**Comment by wizeman** [comment]
Yup, it appears to be fixed now. Thanks!

**Comment by cpitclaudel** [comment]
Great, thanks for the report!
