### ISSUE TITLE
feature request: #done-kill

### ISSUE THREAD

**Issue by msprotz** [FStarLang/fstar-mode.el#33]
I'd like to have a third possible outcome, that says "please display this error message, then kill the fstar process". Would it be hard to implement?

(Granted, I could rework the F\* code to be able to do this without a third message, but it's a lot of work and `#done-kill` seems like a useful feature to have.)

Thanks,

Jonathan

**Comment by cpitclaudel** [comment]
Well, it should either be very easy, or be a very good sign that the implementation needs some work :) Wanna push a prototype to some branch and I'll try it this week-end?

Suggestion: `#done kill` might read better, and it would be consistent with `#done ok` and `#done ok` and `#done nok`.

Other suggestion: you could just kill the process on your side (don't know how much the current code would like that).

**Comment by cpitclaudel** [comment]
Alternative suggestion! Implement everything listed here: https://sympa.inria.fr/sympa/arc/coqdev/2016-05/msg00026.html :)

**Comment by cpitclaudel** [comment]
Hey @msprotz, do you still need this? I can help with the implementation, if needed.

**Comment by cpitclaudel** [comment]
The new protocol handles failures that way.
