### ISSUE TITLE
Difficulty installing from source

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/fstar-mode.el#35]
I'm trying to install fstar-mode.el from source rather than from melpa. 

It fails while trying to evaluate `(require dash)`

I've tried to `M-x package-install dash`, but melpa doesn't seem to know about it.

Any suggestions?

**Comment by nikswamy** [comment]
Update: I had to explicitly download dash.el and add it to my load path. 

This version   
https://github.com/magnars/dash.el/commit/b7ba21202ec876775768fca08163e2cbfd130799
doesn't seem to work. It causes fstar-mode.el to fail with something like `sequencep wrong type argument` (roughly).

I needed to copy dash.el from dash-20160306.1222

**Comment by cpitclaudel** [comment]
Hmm.  `dash` should be available from MELPA (and I'd recommend installing it from there, otherwise it won't be byte-compiled). Try running `M-x list-packages` first maybe?

**Comment by nikswamy** [comment]
I tried `M-x package-list-packages` and that didn't show `dash` in the list. `M-x list-packages` did. Now, I have trouble using both of these: If I try, say, to uninstall `fstar-mode` by selecting `d`, it doesn't add a mark ... so the following `x` doesn't do anything. I guess that's got nothing to do with `fstar-mode.el` per se. 

Is there a reliable way to uinstall fstar-mode.el without having to go through this buggy package manager? Would deleting stuff related to `fstar-mode.el` from `.emacs.d` do it?

**Comment by cpitclaudel** [comment]
> Would deleting stuff related to fstar-mode.el from .emacs.d do it?

Yup; in fact, packages are no more than a folder extracted to `~/.emacs.d/elpa/`.  Deleting that directory removes the package.

**Comment by cpitclaudel** [comment]
I'll assume this is fixed :) Note that with recent changes you need a few more packages, including `quick-peek`, `flycheck`, `company`, `yasnippet`, and `company-quickhelp`
