### ISSUE TITLE
cygwin vs. windows line endings when parsing version

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/fstar-mode.el#40]
Hi Clement, 

Many of us use cygwin emacs with a native windows F* using OCaml. 

It turns out that in this configuration, fstar-mode.el is unable to parse the version of F*. It complains with

```version-to-list: Invalid version syntax: '0.9.3.1-beta^M'```

Notice the suspicious trailing `^M`.

Could this be handled within fstar-mode.el, perhaps getting it to trim the string before parsing it?

Thanks, 
Nik

**Comment by cpitclaudel** [comment]
Thanks for the report.  Should be fixed now.
