### ISSUE TITLE
fstar-mode.el release matching F* release

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/fstar-mode.el#47]
I'm wondering whether it would be possible to tag an fstar-mode.el release corresponding to the new F* release we did yesterday, so that people who want to use the binary package have some chance to also use a working version of the interactive mode. This would increase the value of our releases and thus motivate us to release some more :)

**Comment by s-zanella** [comment]
That's a great idea!
At the very least, we should document which version of fstar-mode.el works with an F* release.

**Comment by catalin-hritcu** [comment]
Did an fstar-mode.el release corresponding to F* v0.9.4.0
https://github.com/FStarLang/fstar-mode.el/releases/tag/V0.9.4.0
Hope that everyone's OK with this.

**Comment by s-zanella** [comment]
Is the release also tagged in MELPA in some way?
How can a user of F* v0.9.4.0 download the right package using MELPA?

**Comment by catalin-hritcu** [comment]
No clue about Melpa. Maybe @cpitclaudel can help with that?

**Comment by cpitclaudel** [comment]
Hi all,

Thanks Catalin for pushing a tag.  Tags are automatically picked up by MELPA *stable* (a variant of MELPA that doesn't track projects' master branch), which means that fstar-mode is now available to users of MELPA stable (I'm not sure it was before).  There are not that many users of MELPA stable, though, so all of this isn't too important.

More to the point: Emacs' package manager doesn't let you get anything but the latest version of a package; the usual approach is just to support all relevant versions in the same package.  I added version detection to fstar-mode, so we should be able to handle any discrepancies between versions in there.

Are there concrete problems in fstar-mode currently (that is, are there still-in-use versions of F* that it doesn't work with?)

**Comment by s-zanella** [comment]
Barring minor bugs, fstar-mode is currently compatible with F* master and v0.9.4.0. 
I think that keeping fstar-mode compatible with the latest F* release is enough. 
Having tagged versions of fstar-mode in MELPA stable for older F* releases is a nice plus.

**Comment by cpitclaudel** [comment]
> Barring minor bugs, fstar-mode is currently compatible with F* master and v0.9.4.0.

Thanks. Pointers to these (I haven't been very good at keeping up lately) would be appreciated, so I can fix them :)

**Comment by s-zanella** [comment]
The ones I recall are #43 and #46.

**Comment by cpitclaudel** [comment]
Ok, I think #43 and #46 are now fixed :)
