### ISSUE TITLE
Auto-fill in comments

### ISSUE THREAD

**Issue by kkohbrok** [FStarLang/fstar-mode.el#48]
It would be nice to have automatic line breaks happening in comments when the line grows too long. From what I could find on that subject, it is already implemented in modes for other languages. Not sure if this is feasible to do, but I think this would be a useful feature.

**Comment by cpitclaudel** [comment]
Are you thinking of `M-x auto-fill-mode`?

**Comment by kkohbrok** [comment]
Yes, except that it only applies in a comment environment: (* .... *) or line //. such that if I type normal code, lines _don't_ get wrapped and if I type an actual text (such as in a comment), lines _do_ get wrapped.

**Comment by cpitclaudel** [comment]
`comment-auto-fill-only-comments`? :)

**Comment by kkohbrok** [comment]
Amazing, thank you! 

How did I miss this? Is that a standard thing in every mode? If not, then it might be worth mentioning on the Readme page. Or set it by default? I don't know how well it plays with fsdoc, though.

**Comment by cpitclaudel** [comment]
I think it's pretty standard, yes :) https://www.gnu.org/software/emacs/manual/html_node/emacs/Auto-Fill.html

**Comment by cpitclaudel** [comment]
In fact, it was the subject of an early request: https://github.com/FStarLang/fstar-mode.el/issues/15

**Comment by kkohbrok** [comment]
Ok, I guess I have to search more thoroughly next time. Thanks again!

**Comment by cpitclaudel** [comment]
No problem. Happy to help :)
