### ISSUE TITLE
Minor syntax highlighting issues

### ISSUE THREAD

**Issue by beurdouche** [FStarLang/fstar-mode.el#49]
Hi Clement @cpitclaudel ! Just decided to fill some nits in the syntax highlighting that I find annoying. If you have time at some point could you have a look ? Clearly this is not an emergency... ;) Thanks a lot ! B.

<img width="749" alt="screen shot 2017-02-20 at 8 13 33 pm" src="https://cloud.githubusercontent.com/assets/1193431/23138932/5aae2aec-f7aa-11e6-8a5a-caafe26d30bc.png">

**Comment by cpitclaudel** [comment]
Thanks for pointing these out! Can you try the 49-fix-syntax-highlighting branch?  It has a fix for the first one — the second one is trickier.

Does F* have any sort of extensible syntax (in the style of Coq's extensible parsing)?

**Comment by beurdouche** [comment]
@cpitclaudel Thanks Clement, I have used it yesterday and today and this branch seems to work fine, haven't encountered any glitches :) To my knowledge no F* doesn't have extensible syntax but I don't know all corners of the compiler itself.

**Comment by beurdouche** [comment]
Actually it seems that I have trouble in some cases...
<img width="640" alt="screen shot 2017-02-23 at 8 15 10 pm" src="https://cloud.githubusercontent.com/assets/1193431/23275006/13ad390a-fa05-11e6-91fb-a011651d05b9.png">

**Comment by cpitclaudel** [comment]
I see, thanks.  Can you post the text so I can copy it?

**Comment by beurdouche** [comment]
```module Test

assume type t

private val blah:
  b:buffer t{length b = 1} ->
  Stack unit
        (requires (fun h -> live h b))
        (ensures (fun h0 _ h1 -> live h1 b /\ modifies_1 b h0 h1))
```

**Comment by cpitclaudel** [comment]
Thanks, that should be fixed too; I force-pushed.

**Comment by beurdouche** [comment]
Yep, looks much better ;) Thanks

**Comment by cpitclaudel** [comment]
Things should be better now, though the `let x, y = …` is still fragile: it's tricky to tell `let f x =` from `let x, y =`.  OTOH fun's and forall's should have better looking arguments now.
