### ISSUE TITLE
Subscripts?

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/fstar-mode.el#6]
Any chance we could render things like `x_0`, `y_1` etc. with subscripts?

**Comment by cpitclaudel** [comment]
Done! Does this match what you had in mind?

**Comment by nikswamy** [comment]
Cool! Thanks for tackling this so quickly.

Some observations/suggestions:

1. `x_1` renders by putting both the `_` and the `1` in subscript. Is it possible to swallow the `_` and just show the `1` ?

2. Things like `x_1=0` do not trigger the subscript on the LHS.

3. `x_1=x_2` triggers the subscript on the RHS, but not the LHS.

4. `x_1 =x_2` triggers the subscript on the LHS but not the RHS

5. `x_1 = x_2` subscripts both sides.

**Comment by cpitclaudel** [comment]
My pleasure :) I fixed 2,3,4,5. Let me see 1.

**Comment by cpitclaudel** [comment]
This seems to work ok. Could you give it a try and see it it feels right? Interaction is always a bit tricky when some characters are made invisible.

**Comment by nikswamy** [comment]
Looks good! Thanks

**Comment by cpitclaudel** [comment]
Great!
