### ISSUE TITLE
F* mode considerable slow down on large files commented using //

### ISSUE THREAD

**Issue by beurdouche** [FStarLang/fstar-mode.el#62]
When commenting with the recent `//` syntax change, my emacs gets a huge slow down.
This was not the case before with the `(* *)` style of comments :)

**Comment by cpitclaudel** [comment]
Hi @beurdouche,

Can you give a concrete example? I haven't noticed the slowdown here :)

Thanks!

**Comment by beurdouche** [comment]
Hey @cpitclaudel !
As an example, you can take `/opt/hacl-star/code/hash/Hacl.Hash.SHA2_512.fst`, comment the file and then try to navigate in it... This is super slow in my setting :)

**Comment by cpitclaudel** [comment]
Thanks! Will look into it soon.

**Comment by cpitclaudel** [comment]
Ok, I pushed a tentative fix.

**Comment by cpitclaudel** [comment]
Please try it and let me know

**Comment by beurdouche** [comment]
Cool ! Will test, Thanks a lot !
