### ISSUE TITLE
Feature request: highlight cheating commands

### ISSUE THREAD

**Issue by tchajed** [FStarLang/fstar-mode.el#66]
Porting this feature from Proof General would be useful to keep track of when a proof doesn't actually work.

I think the identifiers to highlight are `assume`, `admit()`, `magic`, `unsafe_coerce`, and `admitP`, based on looking at [prims.fst](https://github.com/FStarLang/FStar/blob/eca7c05d4f296586a86c110213fdc0cc27c63b54/ulib/prims.fst#L270-L277).

**Comment by cpitclaudel** [comment]
Sounds good.  In the meantime, you can put this in your fstar-mode-hook:

```
(font-lock-add-keywords nil `((,(regexp-opt '("assume" "admit" "admitP" "magic" "unsafe_coerce") 'symbols) . font-lock-warning-face)))
```
