### ISSUE TITLE
Autocompletion is too eager after in and with

### ISSUE THREAD

**Issue by tchajed** [FStarLang/fstar-mode.el#67]
company-coq has special handling of in and with at the end of the line to avoid providing autocompletions when typing `let` and `match` constructs. F* has the same issue:

```
module Test

let _ = let foo = 1 in
        foo

let with_const = 1

let _ = match 1 with
        | 1 -> true
```

Typing the above will result in `in` being auto-completed to `int` upon hitting enter. Once `with_const` as been processed, `with` will auto-complete to `with_const` (in practice the problematic identifier for me is `FStar.HyperStack.ST.with_frame`).

**Comment by tchajed** [comment]
I'll give this a try at some point, given @cpitclaudel showed me the relevant company-coq code while writing https://github.com/cpitclaudel/company-coq/pull/165.

**Comment by cpitclaudel** [comment]
I'm +1 on doing this soon; it's a pain

**Comment by cpitclaudel** [comment]
Let me know if you need help

**Comment by cpitclaudel** [comment]
Any news on this?

**Comment by catalin-hritcu** [comment]
I concur that keywords should always take precedence over longer(!) names from the library. Without this autocompletion is so much a pain that I feel like just switching it off completely. In part this pain is also caused by the emacs mode taking over the enter key, while I use for ending a line. Isn't enough to have tab for autocompletion; what's the rational for taking over enter? When I'm at the end of a line, do I really need to hit Ctrl+G or Esc-Esc-Esc to get rid of useless autocompletion before I can break a line?

**Comment by tchajed** [comment]
@cpitclaudel feel free to take this over, since I'm not doing anything in F* right now

**Comment by cpitclaudel** [comment]
> I concur that keywords should always take precedence

I think we're all in violent agreement here.

> over longer(!) names from the library.

Not sure what `(!)` means :/

> Without this autocompletion is so much a pain that I feel like just switching it off completely.

There's a setting to turn autocompletion off in `fstar-enabled-modules`, which you can get to using `M-x customize`.

> In part this pain is also caused by the emacs mode taking over the enter key, while I use that for ending a line.

That's easy to disable: 

```elisp
(with-eval-after-load 'company
  (define-key company-active-map [return] nil)
  (define-key company-active-map (kbd "RET") nil))
```

>  Isn't enough to have tab for autocompletion; what's the rational for taking over enter? 

Tab doesn't do the same as ret.  Other than this, I don't know: it's a company setting unchanged in fstar-mode (IOW, I didn't pick that default).  See `C-h v company-active-map`.

> When I'm at the end of a line, do I really need to hit Ctrl+G or Esc-Esc-Esc to get rid of useless autocompletion before I can break a line? 

See above. Does that help?

**Comment by catalin-hritcu** [comment]
> > In part this pain is also caused by the emacs mode taking over the enter key, while I use that for ending a line.
> 
> That's easy to disable: 
> 
> ```elisp
> (with-eval-after-load 'company
>   (define-key company-active-map [return] nil)
>   (define-key company-active-map (kbd "RET") nil))
> ```

Awesome! Many thanks. Wouldn't making this be the default solve this issue?

> >  Isn't enough to have tab for autocompletion; what's the rational for taking over enter? 
> 
> Tab doesn't do the same as ret.

Interesting, so what's the difference?
