### ISSUE TITLE
Rendering || as \/, && as /\ is questionable

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/fstar-mode.el#7]
`||` and `&&` are Boolean connectives; `\/` and `/\` are propositional connectives. Conflating them in the rendering is perhaps a bit confusing.

**Comment by cpitclaudel** [comment]
Agreed. Suggestions on which ones should get the pretty rendering? I vote for prettifying `/\` and `\/`. I've disabled prettification for the other two, at least for now.

**Comment by catalin-hritcu** [comment]
Prettifying only `/\` and `\/` is good.
