### ISSUE TITLE
Errors from lack of dbus on macOS

### ISSUE THREAD

**Issue by tchajed** [FStarLang/fstar-mode.el#70]
`fstar--notify-overlay-processed` makes a call to `notifications-notify`, which requires dbus, which does not ship with macOS. This results in a frequent error message:

```
error in process filter: dbus-call-method: peculiar error: "Emacs not compiled with dbus support"
error in process filter: peculiar error: "Emacs not compiled with dbus support"
```

whenever processing finishes.

The easiest solution would be to disable these notifications if dbus isn't available, or support native macOS notifications.

**Comment by cpitclaudel** [comment]
Snap, how unpleasant.

**Comment by cpitclaudel** [comment]
Let me look into this :) Sorry for the trouble.

**Comment by cpitclaudel** [comment]
Can you confirm that `(featurep 'dbusbind)` is `nil` for you?

**Comment by tchajed** [comment]
`(featurep 'dbusbind)` is `nil`, although `(featurep 'dbus)` is `t`.

**Comment by cpitclaudel** [comment]
Perfect, thanks!
