### ISSUE TITLE
Highlighting from SMT solver responses obscures precise error feedback

### ISSUE THREAD

**Issue by tchajed** [FStarLang/fstar-mode.el#71]
F* now gives general feedback about why the SMT solver failed, which does not have a precise location, sometimes in addition to giving a precise assertion failure. It's hard to see the error highlight (red) with the warning highlighting (orange):

<img width="590" alt="screen shot 2017-08-15 at 10 26 57 am" src="https://user-images.githubusercontent.com/1255037/29310162-9d036194-81a4-11e7-87ef-13c08efeb3e4.png">

Line 67 has an error overlay for `off` where there's a good subtyping checked failed error, but it's barely visible.

Perhaps the warning overlay should not be applied if there's an error in the same range? That or the error+warning face should be more distinct than the adjacent warning face.

**Comment by cpitclaudel** [comment]
Yuck yuck. Thanks for pointing the problem out. Can you provide an example input file, so I can experiment with solutions?

**Comment by cpitclaudel** [comment]
Ping :)
