### ISSUE TITLE
Printing the goal fails if it has percent signs

### ISSUE THREAD

**Issue by tchajed** [FStarLang/fstar-mode.el#74]
Looks like `fstar-tactics--insert-goal` doesn't escape the goal, directly using it as a format string. Evaluating the following results in the goal not being printed and an error "apply: Not enough arguments for format string".

```
module Percent_goal

open FStar.Tactics

let op_Percent = op_Addition

let foo () : Lemma True =
  assert_by_tactic (1%1 == 2) (dump "")
```

**Comment by tchajed** [comment]
Credit goes to @nickgian for finding this and identifying format strings as the problem.

**Comment by cpitclaudel** [comment]
Thanks. How silly.

**Comment by cpitclaudel** [comment]
I've pushed a slightly safer fix, too.
