### ISSUE TITLE
Lexical argument shadows the dynamic variable

### ISSUE THREAD

**Issue by andreas-roehler** [FStarLang/fstar-mode.el#79]
Got several compiler warnings, will send a PQ fixing it.

fstar-mode.el:89:1:Warning: Lexical argument shadows the dynamic variable string
fstar-mode.el:89:1:Warning: Lexical argument shadows the dynamic variable string
fstar-mode.el:2327:1:Warning: Lexical argument shadows the dynamic variable string
fstar-mode.el:2331:1:Warning: Lexical argument shadows the dynamic variable string

**Comment by cpitclaudel** [comment]
Hmm. What context are you testing this in? I can't repro these warnings in emacs 24.5, 25, or 26.

**Comment by andreas-roehler** [comment]
On 08.11.2017 21:06, Clément Pit-Claudel wrote:
>
> Hmm. What context are you testing this in? I can't repro these 
> warnings in emacs 24.5, 25, or 26.
>
>

Being on

GNU Emacs 25.1.91.1 (i686-pc-linux-gnu, GTK+ Version 3.14.5) of 2017-01-02

**Comment by cpitclaudel** [comment]
Proof General was incorrectly adding a `(defvar string)` a while ago, causing this warning. It was fixed on the PG side.  Thank for the report!
