### ISSUE TITLE
Support for single line comments

### ISSUE THREAD

**Issue by beurdouche** [FStarLang/fstar-mode.el#8]
Lines commented by // are not coloured in red =)

**Comment by cpitclaudel** [comment]
Should they? Aren't they regular comments?

**Comment by s-zanella** [comment]
It works fine for me. Single line comments are coloured the same way as (* .. *) blocks.

**Comment by beurdouche** [comment]
Santiago, my emacs mode is up-to-date, and I have this …

**Comment by jkzinzindohoue** [comment]
It also works for me (using Windows at the moment).

**Comment by cpitclaudel** [comment]
@beurdouche Maybe you could post a screenshot?

**Comment by beurdouche** [comment]
It was stripped from my email reply sorry, here it is

![screen shot 2015-09-09 at 15 40 34](https://cloud.githubusercontent.com/assets/1193431/9763291/291df158-5709-11e5-94a6-52655e2e54ac.jpg)

**Comment by cpitclaudel** [comment]
Thanks! I forgot that red was the default color for comments in the standard theme.
Did you install the package from git or using the snippet on the README page? If it's the snippet, you probably just need to do it again :)

**Comment by beurdouche** [comment]
Ok, I used the git at first, after reinstalling using the new README, this is working fine ! I think you can close.
Thanks !! =)

**Comment by cpitclaudel** [comment]
Great!
