### ISSUE TITLE
Bringing back (* Coq style *) comments

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/fstar-mode.el#85]
Is there any way I can get back (* Coq style *) comments? I often use `comment-region` / `uncomment-region` and for that I find Coq style comments to be much superior to the current `//` comments. In particular, the regions I want to comment out and back in are often only part of a line or start with part of a line, in which case Coq style comments can be added in and removed without destroying the existing line structure and indentation of the code.

**Comment by cpitclaudel** [comment]
This should do it:

```
(add-hook 'fstar-mode-hook
          (lambda () (setq-local comment-start "(* "
                            comment-continue ""
                            comment-end " *)")))
```

Want a setting?

**Comment by catalin-hritcu** [comment]
If it worked this would be good enough for me. It gives the following error though:
```
Eager macro-expansion failure: (wrong-number-of-arguments (2 . 2) 6)
```
And an option would probably be nice in general :)

**Comment by cpitclaudel** [comment]
If it happens at startup, you can start emacs with --debug-init (`emacs --debug-init`).  If it happens during normal operation, you can run `M-x toggle-debug-on-error` before reproducing the issue.

**Comment by cpitclaudel** [comment]
Oh, I think I know what's happening. Try this:

```elisp
(add-hook 'fstar-mode-hook
          (lambda ()
            (setq-local comment-start "(* ")
            (setq-local comment-continue "")
            (setq-local comment-end " *)")))
```
