### ISSUE TITLE
Missing python script from ELPA installation

### ISSUE THREAD

**Issue by jeb2239** [FStarLang/fstar-mode.el#87]
I believe there is supposed to be a python script install with this mode but it doesn't come up when installed from ELPA

**Comment by cpitclaudel** [comment]
Which python script are you thinking about?

**Comment by jeb2239** [comment]
![image](https://user-images.githubusercontent.com/5044729/39847586-5ee5ae54-53d0-11e8-8c01-ed8532612377.png)
fstar-literate?

**Comment by cpitclaudel** [comment]
Closing this, since the package should have that file; feel free to reopen if it still happens.
