### ISSUE TITLE
Individual line comments disrupt interactive mode

### ISSUE THREAD

**Issue by parno** [FStarLang/fstar-mode.el#88]
The code below has a comment in the midst of a match statement.  From the command line, F* is perfectly happy.  In interactive mode, F* reports an incomplete match.  Interestingly, the issue disappears if I indent the comment.  

In case it's useful, I've included the source file [IncompleteSmall.txt](https://github.com/FStarLang/fstar-mode.el/files/1992884/IncompleteSmall.txt) and an IDE transcript [test.txt](https://github.com/FStarLang/fstar-mode.el/files/1992885/test.txt)  (with renamed file extensions -- thanks GitHub).

```
module IncompleteSmall

type ins =
  | A      : a:int -> ins
  | B      : b:int -> ins

let eval_ins (ins:ins) : int =
  match ins with
  | A a -> 0

// Useful comment here

  | B b -> 1
```

**Comment by cpitclaudel** [comment]
Thanks. That's a known issue (design decision? ^^)

It boils down to segmenting F* code into individual definitions.  The question is: how do you tell what's a unit of F* code? The CLI gets to run the F* parser to determine fragment boundaries, but we don't have that luxury in the interactive mode, so the current approach looks for sigelt starters in column 0, or comments, preceded by empty lines (which is why indenting the comment or removing the blank line before it solves the issue) 

One solution could be to stop recognizing comments in column zero as block starters, but then you run into this issue:

```
// Some witty comment here
let a = 1
```

Now `//` isn't a block starter anymore, but neither is `let a = 1`.  We can of course start recognizing all lets in column 0 as definition starters, but now we have another issue:

```
let x =
let y = 1 in
x + x
```

… this gets split as `let x =`, and then a separate fragment starting at `let y =`.

All of this isn't ideal.  I've added a segment command to the IDE mode which takes a fragment of code and cuts it up into fragments — I'd love to use that, but the problem is that often when you do a push F* is busy, so you can't call it to ask it to segment your file.  You could have a second instance of F* running just for parsing purposes, but that seems heavy-handed.

Note though that you can use C-u C-c C-RET to process up to the current point as one unit.

Let me know if you have ideas to make this better.

**Comment by parno** [comment]
Just to make sure I'm following you, it sounds like you're attempting to do a lightweight parse of F* code in order to segment it into definitions.  The current heuristics for parsing are fooled by a column 0 comment.  

If that's correct, then it sounds like you can either continue to tweak the heuristics or integrate the F* parser in some form (perhaps someday we could extract a version of F* that only includes the parser?).  The former seems like it will always be subject to some mismatch with F*'s version, so maybe the best thing you can do is document the heuristics somewhere and leave it at that.

**Comment by cpitclaudel** [comment]
> Just to make sure I'm following you, it sounds like you're attempting to do a lightweight parse of F* code in order to segment it into definitions

Correct

> The current heuristics for parsing are fooled by a column 0 comment.

Yes, when preceded by a blank line

> or integrate the F* parser in some form (perhaps someday we could extract a version of F* that only includes the parser?).

I'd need an Elisp version, though, not OCaml

> The former seems like it will always be subject to some mismatch with F*'s version

Ah, good point, yup.

> maybe the best thing you can do is document the heuristics somewhere and leave it at that.

OK, will do.

**Comment by parno** [comment]
> I'd need an Elisp version, though, not OCaml

F* already has two backends -- how hard could a third be?  :)

**Comment by cpitclaudel** [comment]
> F* already has two backends -- how hard could a third be? :)

Right, and since ELisp has neat and clean semantics, translating will be a breeze.

**Comment by cpitclaudel** [comment]
> The case of mutually recursive definitions can be quite annoying

An easy solution is to write it like this:

```
// some
let rec foo () : ML unit = bar ()
// 
// thing
and bar () : ML unit = foo ()
```

or like this:

```
// some
let rec foo () : ML unit = bar () 
// thing
and bar () : ML unit = foo ()
```

```
let rec foo () : ML unit =
  // some
  bar () 
and bar () : ML unit = 
  // thing
  foo ()
```

Having to use workarounds isn't great, of course.

> and puzzling to the unaware user

Yup, I think that's the main problem :/

> BTW, couldn't you just consider lines with only comments equivalent to empty ones?

It's not that easy :/ Comments before a definition are part of the same logical block as that definition, so the start of a block really is the comment, not the `let`.

It's always possible to improve the heuristic, of course… can you try adding the following to your .emacs? (@parno, it would be nice if you could give it a try too)

```
(require 'fstar-mode)

(defun fstar-subp--likely-block-start-p ()
  "Check whether the current match looks like a block start."
  (and
   ;; Skip block starters in comments
   (not (fstar-in-comment-p (match-beginning 1)))
   ;; Skip false positives introduced by considering ‘^//’ a block starter
   (save-excursion
     (goto-char (match-beginning 0))
     (while (forward-comment 1))
     (skip-chars-backward fstar--spaces)
     (looking-at-p fstar-subp-block-sep))))

(defun fstar-subp--block-start-p ()
  "Check whether the current match is a valid block start."
  (and (not (= (match-beginning 1) (point-max)))
       (fstar-subp--likely-block-start-p)))

(defun fstar-subp--block-end-p ()
  "Check whether the current match is a valid block end."
  (and (not (= (match-beginning 0) (point-min)))
       (fstar-subp--likely-block-start-p)))
```

**Comment by cpitclaudel** [comment]
Ping. I'd like to push the new heuristic, but having a regular test it first would be helpful

**Comment by cpitclaudel** [comment]
Thanks a lot.  Here's an updated patch:

```
(require 'fstar-mode)

(defconst fstar-subp-block-start-re
  (format "\\`\\|%s\\(?:\\'\\|^\\(?:%s\\)\\)" fstar-subp--blanks-re fstar-syntax-block-start-re))

(defun fstar-subp--likely-block-start-p ()
  "Check whether the current match looks like a block start."
  (and
   ;; Skip block starters in comments
   (not (fstar-in-comment-p (match-beginning 1)))
   ;; Skip false positives introduced by considering ‘^//’ a block starter
   (save-excursion
     (goto-char (match-beginning 0))
     (while (forward-comment 1))
     (skip-chars-backward fstar--spaces)
     (looking-at-p fstar-subp-block-start-re))))

(defun fstar-subp--block-start-p ()
  "Check whether the current match is a valid block start."
  (and (not (= (match-beginning 1) (point-max)))
       (fstar-subp--likely-block-start-p)))

(defun fstar-subp--block-end-p ()
  "Check whether the current match is a valid block end."
  (and (not (= (match-beginning 0) (point-min)))
       (fstar-subp--likely-block-start-p)))
```

**Comment by parno** [comment]
I tried this out on the file with the complicated example above, and it now behaves as expected.  I've done a small amount of other F* verification work after applying the patch, and I haven't seen any other unexpected behavior yet, but it's a fairly small sample.  (Sorry for the delayed response -- I've been traveling and working on Vale stuff instead of F*.)

**Comment by cpitclaudel** [comment]
Thanks for confirming!
