### ISSUE TITLE
Highlight assume/admit?

### ISSUE THREAD

**Issue by parno** [FStarLang/fstar-mode.el#91]
Would it be possible to highlight (via enlarged/bold text or scary emoticons), uncommented calls to `assume` or `admit`?  It might help avoid those situations where all of your proofs start going through super smoothly, only you later realize that you left in an `admit` while debugging earlier.  Not that it's ever happened to me of course.  Asking for a friend.

**Comment by cpitclaudel** [comment]
Good idea.  "admit" et al should already be displayed in a different font, but I've just made that font customizable (`M-x customize-face fstar-risky-face`).  Should we make it look scarier by default, too?

**Comment by cpitclaudel** [comment]
Good point, thanks.  `assume` is a special case because of `assume val …`.  How should that be highlighted?

**Comment by beurdouche** [comment]
I would treat `assume` the same way `admit` is. : )

**Comment by cpitclaudel** [comment]
OK, just pushed this:

![image](https://user-images.githubusercontent.com/8181630/42424856-c225f1fa-82e1-11e8-9a46-2b5115950e2e.png)

**Comment by beurdouche** [comment]
Cool, the `assume` part from the `assume val` is not dangerous though,
but if it is ok for everyone, keeping it that way is fine with me : )

**Comment by cpitclaudel** [comment]
> Cool, the assume part from the assume val is not dangerous though,

I'm confused, didn't you mean the opposite when you wrote "I would treat assume the same way admit is."?

**Comment by beurdouche** [comment]
My bad the sentence should have been "I would treat assume *alone* the same way admit is. : )"

**Comment by cpitclaudel** [comment]
Ah, OK. Why is `assume val` safe?

**Comment by beurdouche** [comment]
Well actually not that much, it is true. In most cases I use `assume val` for unimplemented functions or "external" functions. I didn't immediately realize because I always give a `let` and an `admit` for my admitted lemmas but because we can `assume val` a lemma or whatever, it can also be unsafe...
As I said this is a great change, I am totally fine with it ! Thanks Clément ;)

**Comment by parno** [comment]
I agree that it's okay to default to highlighting `assume val` as well.  If it's an assumption about the external world, then you're not likely to remove it, but highlighting it would help you or a future reader notice the assumptions you've added.

On a separate note, FWIW, I think I'm up-to-date (I have version `20180708.1438` of fstar-mode), but my display still looks the same as before.  This is Aquamacs though.  When I try it in Emacs, it looks like Clement's display above, so it must be an Aquamacs thing.

**Comment by cpitclaudel** [comment]
Great, thanks.

**Comment by cpitclaudel** [comment]
> On a separate note, FWIW, I think I'm up-to-date (I have version 20180708.1438 of fstar-mode)

Try updating again (MELPA doesn't build immediately after code is committed) :)

**Comment by cpitclaudel** [comment]
Thanks!
